### ISSUE TITLE
reports that sampledata step hangs

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-ansible#22]
suspect the switch to centos8. test this.

**Comment by donsizemore** [comment]
@pdurbin just ran this through on CentOS8 in Vagrant - it succeeds, though I see a bunch of:

`Lock found for dataset id 40`

which is "CMS Fabricated Data" containing 10 sizable tabular files. will test in EC2 next.

**Comment by donsizemore** [comment]
@pdurbin sampledata succeeded on CentOS8 in EC2 as well, same bunch of `Lock found for dataset id 40... sleeping...` though.

If anyone has further trouble with sampledata hanging I'd request more info: platform/OS, other group_var features enabled, logs... closing.

**Comment by pdurbin** [comment]
I'm still seeing this problem but my plan is to push a branch with a config file to only load the sample data I need for the memory tests I'm working on in https://github.com/IQSS/dataverse/issues/7089

That is, something like this:

```
  sampledata:
    enabled: true
    dir: /tmp/sampledata
    repo: https://github.com/IQSS/dataverse-sample-data.git
    branch: 7089-memory-tests
    venv: /tmp/sampledata/venv
```
