### ISSUE TITLE
/usr/local/glassfish5 vs /usr/local/payara5

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#24]
If we use `/usr/local/payara5` it will match upstream Dataverse 5. For context, here's the part of default/main.yml I'm talking about:

```
  glassfish:
    user: dataverse
    group: dataverse
    domain: domain1
    logformat: ulf
    adminuser: admin
    adminpass: notPr0d
    siteurl:
    timeout: 180
    request_timeout: 1800
    root: /usr/local
    dir: glassfish5
    zipurl: https://github.com/payara/Payara/releases/download/payara-server-5.2020.2/payara-5.2020.2.zip
    zipchecksum: sha256:1f5f7ea30901b1b4c7bcdfa5591881a700c9b7e2022ae3894192ba97eb83cc3e
```

I'm wondering how we feel about changing "dir" from "glassfish5" to "payara5".
