### ISSUE TITLE
Parts of role rely on connection being local

### ISSUE THREAD

**Issue by janvanmansum** [GlobalDataverseCommunityConsortium/dataverse-ansible#25]
It seems that some parts of the role rely on ansible being run on the target machine (controlled machine). The Vagrantfile explicitly uses `:ansible_local` for example. Another example is in `tasks/dataverse-postinstall.yml`: 

```yaml
- name: grab custom metadata blocks
  get_url:
    url: '{{ item }}'
    dest: /tmp/dataverse/custom_metadata_blocks
  loop: '{{ dataverse.custom_metadata_blocks.urls }}'
  when: dataverse.custom_metadata_blocks.enabled == True

- name: read custom metadata block list
  find:
    path: /tmp/dataverse/custom_metadata_blocks
  register: custom_metadata_block_list

- name: load custom metadata blocks
  uri:
    url: http://localhost:8080/api/admin/datasetfield/load
    method: POST
    headers:
      Content-type: 'text/tab-separated-values'
    body: "{{ lookup('file', item.path) }}"
  loop: '{{ custom_metadata_block_list.files }}'
  when: dataverse.custom_metadata_blocks.enabled == True
```

`lookup` uses the [file plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/file.html) here, which means that `item.path` must be located on the controller machine. However the `get_url` invocation at the top will download to the *controlled* machine. This will therefore only work if controlled and contoller machine are the same, that is to say if the connection is local.

My question is if this is a design decision (and what the rationale was) or that it is accidental. In the latter case I will try to fix this and make a PR.
