### ISSUE TITLE
Ubuntu 22.04, shibboleth module name changed

### ISSUE THREAD

**Issue by sergejzr** [GlobalDataverseCommunityConsortium/dataverse-ansible#261]
Dear Dataverse community,
when installing Dataverse on Ubuntu 22.05 (most recent LTS), we noticed in /tasks/shibboleth.yml , "libapache2-mod-shib2" should be adjusted to "libapache2-mod-shib" for that OS.

My fix is below. You may find a more elegant solution, though:

```
- name: install Shibboleth for Debian/Ubuntu
  package:
    name: shibboleth-sp2-utils, libapache2-mod-shib2, libapache2-mod-jk
    state: latest
  when: ansible_os_family == "Debian" and ansible_distribution_major_version != "22"

- name: install Shibboleth for Debian/Ubuntu 22
  package:
    name: shibboleth-sp-utils, libapache2-mod-shib, libapache2-mod-jk
    state: latest
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "22"
```
