### ISSUE TITLE
 "set logging format" fail is transport is paramiko

### ISSUE THREAD

**Issue by janvanmansum** [GlobalDataverseCommunityConsortium/dataverse-ansible#31]
# Summary
If the transport is set to "paramiko" the step after the Dataverse installer is run fails.

# Steps
1. Check out #30 
2. Add `transport: "paramiko"` to the Ansible config settings in `molecule/default/molecule.yml`:

    ```yaml
    # ....
    provisioner:
        name: ansible
        playbooks:
           prepare: prepare.yml
           config_options:
           defaults:
              transport: 'paramiko' # <- add this
              remote_tmp: '/tmp'
              hash_behaviour: 'merge'
           ssh_connection:
              pipelining: True
              control_path: '/tmp/ansible-ssh-%%h-%%p-%%r'
    # ....
    ```
3. Run `mol create` and `mol converge`.

# Problem
The role fails after running the DV installer and trying to set the logging format:

```
TASK [dataverse-ansible : allow installer write access] ************************
    changed: [centos8]

    TASK [dataverse-ansible : patch installAppServer.py so that FILES_DIR points to the correct location] ***
    skipping: [centos8]

    TASK [dataverse-ansible : fire off installer] **********************************
    changed: [centos8]

    TASK [dataverse-ansible : set logging format] **********************************
    fatal: [centos8]: FAILED! => {"changed": true, "cmd": "/usr/local/glassfish4/bin/asadmin set-log-file-format ulf", "delta": "0:00:00.388184", "end": "2020-08-07 14:50:58.805843", "msg": "non-zero return code", "rc": 1, "start": "2020-08-07 14:50:58.417659", "stderr": "Remote server does not listen for requests on [localhost:4848]. Is the server up?", "stderr_lines": ["Remote server does not listen for requests on [localhost:4848]. Is the server up?"], "stdout": "No such local command: set-log-file-format.  Unable to access the server to execute the command remotely.  Verify the server is available. \nCommand set-log-file-format failed.", "stdout_lines": ["No such local command: set-log-file-format.  Unable to access the server to execute the command remotely.  Verify the server is available. ", "Command set-log-file-format failed."]}

    PLAY RECAP *********************************************************************
    centos8                    : ok=113  changed=69   unreachable=0    failed=1    skipped=166  rescued=0    ignored=0
```
